import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { describe, expect, it } from "vitest"
import { checkV137ReleaseTag } from "./check-v1-37-release-tag.js"
const git = (root: string, args: string[]) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim()
const archiveFiles = [".planning/ROADMAP.md", ".planning/REQUIREMENTS.md", ".planning/v1.37-MILESTONE-AUDIT.md", ".planning/artifacts/v1.37-prearchive-proof.json", ".planning/artifacts/v1.37-milestone-audit.json", ".planning/artifacts/v1.37-strategy-evaluation-foundation.json"] as const
const sha = (value: Buffer) => `sha256:${createHash("sha256").update(value).digest("hex")}`
const fixture = () => { const root = mkdtempSync(path.join(tmpdir(), "v137-tag-")); git(root, ["init"]); git(root, ["config", "user.email", "fixture@example.invalid"]); git(root, ["config", "user.name", "fixture"]); for (const file of archiveFiles) { mkdirSync(path.join(root, path.dirname(file)), { recursive: true }); writeFileSync(path.join(root, file), "{}\n") } mkdirSync(path.join(root, ".planning/artifacts"), { recursive: true }); const archiveBlobSha256 = Object.fromEntries(archiveFiles.map((file) => [file, sha(readFileSync(path.join(root, file)))])); writeFileSync(path.join(root, ".planning/artifacts/v1.37-release-readiness.json"), JSON.stringify({ releaseState: "release-ready", releaseOperation: { completion: false }, tagMessageFieldSha256: { semanticTupleId: "sha256:" + "a".repeat(64), finalProof: "sha256:" + "b".repeat(64), milestoneAudit: "sha256:" + "c".repeat(64) }, archiveBlobSha256 }) + "\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "archive"]); return { root, commit: git(root, ["rev-parse", "HEAD"]) } }
describe("v1.37 release tag checker", () => {
  it("pretag validates archive membership and never closes PROOF-08", () => { const { root, commit } = fixture(); const result = checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: commit }); expect(result.findings).toEqual([]); expect(result.proof08).toBe(false) })
  it("rejects absent/lightweight/wrong annotated tag targets", () => { const { root, commit } = fixture(); expect(checkV137ReleaseTag({ repoRoot: root }).proof08).toBe(false); git(root, ["tag", "v1.37"]); expect(checkV137ReleaseTag({ repoRoot: root }).findings.map((x) => x.code)).toContain("TAG_NOT_ANNOTATED"); git(root, ["tag", "-d", "v1.37"]); git(root, ["tag", "-a", "v1.37", "-m", "wrong", commit]); expect(checkV137ReleaseTag({ repoRoot: root }).findings.map((x) => x.code)).toContain("TAG_MESSAGE_MISMATCH") })
  it("accepts exactly an annotated readiness-bound unsigned tag", () => { const { root, commit } = fixture(); const body = ["sha256:" + "a".repeat(64), "sha256:" + "b".repeat(64), "sha256:" + "c".repeat(64)].join("\n"); git(root, ["tag", "-a", "v1.37", "-m", body, commit]); expect(checkV137ReleaseTag({ repoRoot: root }).proof08).toBe(true) })
  it("rejects an annotated tag on a previously valid archive after HEAD advances", () => { const { root, commit } = fixture(); const body = ["sha256:" + "a".repeat(64), "sha256:" + "b".repeat(64), "sha256:" + "c".repeat(64)].join("\n"); git(root, ["tag", "-a", "v1.37", "-m", body, commit]); writeFileSync(path.join(root, "new-archive"), "new\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "new archive"]); expect(checkV137ReleaseTag({ repoRoot: root }).findings.map((finding) => finding.code)).toContain("TAG_TARGET_NOT_EXPECTED_ARCHIVE") })
  it("rejects non-root archive commits that change either protected user-owned path", () => { for (const protectedPath of ["CowardsGameSpec_Full_Consolidated_v1.md", ".planning/config.json"]) { const { root } = fixture(); mkdirSync(path.join(root, path.dirname(protectedPath)), { recursive: true }); writeFileSync(path.join(root, protectedPath), "protected\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "protected drift"]); const result = checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }); expect(result.findings.map((finding) => finding.code)).toContain("PROTECTED_PATH_INCLUDED") } })
  it("rejects absent, unknown, and substituted archive blob manifests", () => { const { root, commit } = fixture(); const readinessPath = path.join(root, ".planning/artifacts/v1.37-release-readiness.json"); const readiness = JSON.parse(readFileSync(readinessPath, "utf8")) as Record<string, unknown>; writeFileSync(readinessPath, JSON.stringify({ ...readiness, archiveBlobSha256: undefined }) + "\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "missing manifest"]); expect(checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }).findings.map((finding) => finding.code)).toContain("ARCHIVE_BLOB_MANIFEST_MISSING"); git(root, ["reset", "--hard", commit]); writeFileSync(readinessPath, JSON.stringify({ ...readiness, archiveBlobSha256: { ...(readiness.archiveBlobSha256 as object), "unknown": "sha256:" + "a".repeat(64) } }) + "\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "unknown manifest"]); expect(checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }).findings.map((finding) => finding.code)).toContain("ARCHIVE_BLOB_MANIFEST_INVALID") })
  it("rejects substitution of every required archive blob", () => { for (const file of archiveFiles) { const { root } = fixture(); writeFileSync(path.join(root, file), "substituted\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "substitute blob"]); const result = checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }); expect(result.findings).toContainEqual({ code: "ARCHIVE_BLOB_MISMATCH", path: file }) } })
})
