import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { describe, expect, it } from "vitest"
import { checkV137ReleaseTag } from "./check-v1-37-release-tag.js"
import { createV137ReleaseReadinessFixture } from "./evaluate-v1-37-release-readiness.js"
const git = (root: string, args: string[]) => execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim()
const archiveFiles = [".planning/ROADMAP.md", ".planning/REQUIREMENTS.md", ".planning/v1.37-MILESTONE-AUDIT.md", ".planning/artifacts/v1.37-prearchive-proof.json", ".planning/artifacts/v1.37-milestone-audit.json", ".planning/artifacts/v1.37-strategy-evaluation-foundation.json"] as const
const sha = (value: Buffer) => `sha256:${createHash("sha256").update(value).digest("hex")}`
const fixture = () => { const root = mkdtempSync(path.join(tmpdir(), "v137-tag-")); git(root, ["init"]); git(root, ["config", "user.email", "fixture@example.invalid"]); git(root, ["config", "user.name", "fixture"]); for (const file of archiveFiles) { mkdirSync(path.join(root, path.dirname(file)), { recursive: true }); writeFileSync(path.join(root, file), "{}\n") } mkdirSync(path.join(root, ".planning/artifacts"), { recursive: true }); const archiveBlobSha256 = Object.fromEntries(archiveFiles.map((file) => [file, sha(readFileSync(path.join(root, file)))])); const base = createV137ReleaseReadinessFixture(); const prerequisiteHashes = { ...base.prerequisiteHashes, prearchiveProofSha256: archiveBlobSha256[".planning/artifacts/v1.37-prearchive-proof.json"], milestoneAuditSha256: archiveBlobSha256[".planning/artifacts/v1.37-milestone-audit.json"], strategyFoundationSha256: archiveBlobSha256[".planning/artifacts/v1.37-strategy-evaluation-foundation.json"] }; const readiness = { ...base, prerequisiteHashes, tagMessageFieldSha256: { ...base.tagMessageFieldSha256, finalProof: prerequisiteHashes.prearchiveProofSha256, milestoneAudit: prerequisiteHashes.milestoneAuditSha256 }, archiveBlobSha256 }; writeFileSync(path.join(root, ".planning/artifacts/v1.37-release-readiness.json"), JSON.stringify(readiness) + "\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "archive"]); return { root, commit: git(root, ["rev-parse", "HEAD"]) } }
const tagBody = (root: string): string => { const readiness = JSON.parse(readFileSync(path.join(root, ".planning/artifacts/v1.37-release-readiness.json"), "utf8")) as { tagMessageFieldSha256: Record<string, string> }; return [readiness.tagMessageFieldSha256.semanticTupleId, readiness.tagMessageFieldSha256.finalProof, readiness.tagMessageFieldSha256.milestoneAudit].join("\n") }
describe("v1.37 release tag checker", () => {
  it("pretag validates archive membership and never closes PROOF-08", () => { const { root, commit } = fixture(); const result = checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: commit }); expect(result.findings).toEqual([]); expect(result.proof08).toBe(false) })
  it("rejects absent/lightweight/wrong annotated tag targets", () => { const { root, commit } = fixture(); expect(checkV137ReleaseTag({ repoRoot: root }).proof08).toBe(false); git(root, ["tag", "v1.37"]); expect(checkV137ReleaseTag({ repoRoot: root }).findings.map((x) => x.code)).toContain("TAG_NOT_ANNOTATED"); git(root, ["tag", "-d", "v1.37"]); git(root, ["tag", "-a", "v1.37", "-m", "wrong", commit]); expect(checkV137ReleaseTag({ repoRoot: root }).findings.map((x) => x.code)).toContain("TAG_MESSAGE_MISMATCH") })
  it("accepts exactly an annotated readiness-bound unsigned tag", () => { const { root, commit } = fixture(); git(root, ["tag", "-a", "v1.37", "-m", tagBody(root), commit]); expect(checkV137ReleaseTag({ repoRoot: root }).proof08).toBe(true) })
  it("rejects an annotated tag on a previously valid archive after HEAD advances", () => { const { root, commit } = fixture(); git(root, ["tag", "-a", "v1.37", "-m", tagBody(root), commit]); writeFileSync(path.join(root, "new-archive"), "new\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "new archive"]); expect(checkV137ReleaseTag({ repoRoot: root }).findings.map((finding) => finding.code)).toContain("TAG_TARGET_NOT_EXPECTED_ARCHIVE") })
  it("rejects non-root archive commits that change either protected user-owned path", () => { for (const protectedPath of ["CowardsGameSpec_Full_Consolidated_v1.md", ".planning/config.json"]) { const { root } = fixture(); mkdirSync(path.join(root, path.dirname(protectedPath)), { recursive: true }); writeFileSync(path.join(root, protectedPath), "protected\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "protected drift"]); const result = checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }); expect(result.findings.map((finding) => finding.code)).toContain("PROTECTED_PATH_INCLUDED") } })
  it("rejects absent and unknown archive blob manifests through canonical readiness validation", () => { const { root, commit } = fixture(); const readinessPath = path.join(root, ".planning/artifacts/v1.37-release-readiness.json"); const readiness = JSON.parse(readFileSync(readinessPath, "utf8")) as Record<string, unknown>; writeFileSync(readinessPath, JSON.stringify({ ...readiness, archiveBlobSha256: undefined }) + "\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "missing manifest"]); expect(checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }).findings.map((finding) => finding.code)).toContain("READINESS_INVALID"); git(root, ["reset", "--hard", commit]); writeFileSync(readinessPath, JSON.stringify({ ...readiness, archiveBlobSha256: { ...(readiness.archiveBlobSha256 as object), "unknown": "sha256:" + "a".repeat(64) } }) + "\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "unknown manifest"]); expect(checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }).findings.map((finding) => finding.code)).toContain("READINESS_INVALID") })
  it("rejects substitution of every required archive blob", () => { for (const file of archiveFiles) { const { root } = fixture(); writeFileSync(path.join(root, file), "substituted\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "substitute blob"]); const result = checkV137ReleaseTag({ repoRoot: root, mode: "pretag-archive", archiveCommit: git(root, ["rev-parse", "HEAD"]) }); expect(result.findings).toContainEqual({ code: "ARCHIVE_BLOB_MISMATCH", path: file }) } })
  it("rejects a forged self-consistent readiness and tag that violates the canonical readiness contract", () => { const { root } = fixture(); const readinessPath = path.join(root, ".planning/artifacts/v1.37-release-readiness.json"); const readiness = JSON.parse(readFileSync(readinessPath, "utf8")) as Record<string, unknown>; const forged = { ...readiness, prerequisiteHashes: { ...(readiness.prerequisiteHashes as object), prearchiveProofSha256: "sha256:" + "f".repeat(64) }, tagMessageFieldSha256: { ...(readiness.tagMessageFieldSha256 as object), finalProof: "sha256:" + "f".repeat(64) }, archiveBlobSha256: { ...(readiness.archiveBlobSha256 as object), ".planning/artifacts/v1.37-prearchive-proof.json": "sha256:" + "f".repeat(64) }, forged: true }; writeFileSync(readinessPath, JSON.stringify(forged) + "\n"); git(root, ["add", "."]); git(root, ["commit", "-m", "forged readiness"]); const commit = git(root, ["rev-parse", "HEAD"]); git(root, ["tag", "-a", "v1.37", "-m", tagBody(root), commit]); expect(checkV137ReleaseTag({ repoRoot: root }).findings.map((finding) => finding.code)).toContain("READINESS_INVALID") })
})
