import { createHash } from "node:crypto"
import { readFileSync } from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

const repoRoot = path.resolve(import.meta.dirname, "..")
const read = (relativePath: string): Buffer =>
  readFileSync(path.join(repoRoot, relativePath))
const sha256 = (bytes: Uint8Array): string =>
  createHash("sha256").update(bytes).digest("hex")

describe("versioned TypeScript-to-Go parity generator", () => {
  it("protects immutable v1.16 bytes and exposes only an explicit v1.17 writer", () => {
    const source = read("scripts/generate-go-parity-fixtures.ts").toString("utf8")
    expect(source).toContain('args.includes("--write-v1.17")')
    expect(source).toContain('args.includes("--write-v1.16")')
    expect(source).toContain("Refusing to rewrite immutable v1.16")
    expect(source).not.toContain("writeFileSync(runtimeExecutionWireGoldenPath")

    expect(
      sha256(read("packages/spec/artifacts/runtime-execution-service-request.v1.16.json")),
    ).toBe("5d04fa4d82eb814bb034ce9b5f1d5c80945e3d4e02c9124ca39a6670e9c0eab5")
    expect(
      sha256(read("packages/spec/artifacts/runtime-execution-service-response.v1.16.wire.json")),
    ).toBe("9c870d57e0125eb80ab2ba941ecbbede8a9a775f61c0b278abec25c491374d97")
  })

  it("generates one marked closed version table with deny-by-default dispatch", () => {
    const generated = read("apps/go-backend/runtime_execution_contract_gen.go").toString("utf8")
    expect(generated.match(/Code generated by scripts\/generate-go-parity-fixtures\.ts/g)).toHaveLength(1)
    expect(generated).toContain('"runtime-execution-service-v1.16"')
    expect(generated).toContain('"runtime-invocation-v1.17"')
    expect(generated).toContain("Historical: true")
    expect(generated).toContain("CanonicalJSON: true")
    expect(generated).toContain("runtimeInvocationContractForVersion")

    const writers = [
      "scripts/generate-go-parity-fixtures.ts",
      "scripts/generate-go-parity-fixtures.test.ts",
    ].filter((relativePath) =>
      read(relativePath).toString("utf8").includes("runtime_execution_contract_gen.go"),
    )
    expect(writers).toEqual([
      "scripts/generate-go-parity-fixtures.ts",
      "scripts/generate-go-parity-fixtures.test.ts",
    ])
  })
})
