// Code generated by scripts/generate-v1-37-arena-set-authority.ts; DO NOT EDIT.
package main

import (
	"os"
	"reflect"
	"strings"
	"testing"
)

func TestArenaSetAuthorityV137CandidateProjection(t *testing.T) {
	candidate, ok := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	if !ok { t.Fatal("explicit v1.19 candidate lookup failed") }
	if candidate.SourceSHA256 != "sha256:eb5183d312073a4f90d53988d188688ceec40d12599ca8a03ef23919a73f4f95" || candidate.OutputSHA256 != "sha256:b8029f58ce84bd37b6c9f1bb1fe604d74bf35ea6a0c18b84d67a98e7c04c16d8" { t.Fatal("generated source/output digest drift") }
	if candidate.Tuple.RuntimeABI != "strategy-runtime-abi-v1.19" || candidate.Tuple.ArenaCatalog != "canonical-arena-catalog-v1.37" || candidate.Tuple.SetPolicy != "canonical-set-policy-v1.37-four-condition-v1" { t.Fatal("candidate tuple drift") }
	if len(candidate.Arenas) != 3 || candidate.Arenas[0].ID != "arena:smoke:v1" || candidate.Arenas[1].ID != "arena:standard-cross:v1" || candidate.Arenas[2].ID != "arena:open-field:v1" { t.Fatal("arena catalog membership/order drift") }
	if candidate.Arenas[0].SemanticGeometryHash != candidate.Arenas[2].SemanticGeometryHash || candidate.Arenas[2].AliasOf != candidate.Arenas[0].ID || candidate.Arenas[2].Schedulable { t.Fatal("arena alias semantics drift") }
	if len(candidate.ConditionRows) != 4 || candidate.Policy.ConditionCount != 4 || candidate.Policy.Active || candidate.Policy.SeedCarriesFairnessSemantics || candidate.Policy.PartialMatrixCounts || candidate.Policy.SystemFailureIsTerminalEvidence || !candidate.Policy.RequiresEveryCanonicalCondition || !candidate.Policy.PlayerViolationIsTerminalEvidence { t.Fatal("four-condition policy drift") }
	wantSuffixes := []string{"a-bottom-a-first", "a-bottom-b-first", "a-top-a-first", "a-top-b-first"}
	for index, row := range candidate.ConditionRows { if row.Ordinal != index || row.Suffix != wantSuffixes[index] { t.Fatal("condition membership/order drift") } }
	copyCandidate := candidate
	copyCandidate.Arenas[0].ID = "mutated"
	again, _ := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	if again.Arenas[0].ID != "arena:smoke:v1" { t.Fatal("candidate lookup shared mutable data") }
}

func TestArenaSetAuthorityV137LookupIsExplicitAndCurrentIsClosed(t *testing.T) {
	for _, key := range []string{"", "runtime-v1.17", "runtime-v1.18", "runtime-v1.20"} { if _, ok := arenaSetAuthorityV137CandidateBySemanticAuthorityKey(key); ok { t.Fatalf("unexpected candidate lookup for %q", key) } }
	current := currentSemanticAuthorityGenerated()
	switch current.SemanticAuthorityKey {
	case "runtime-v1.17":
		if current.TupleID != runtimeSuccessorSemanticTupleIDV117 || current.RuntimeABI != "strategy-runtime-abi-v1.17" || current.ArenaCatalog != "semantic-arena-catalog-v1.37-candidate-1" || current.SetPolicy != "canonical-set-policy-v1.4" || current.ConformanceCertificateVersion != "runtime-conformance-certificate-v1.17" || current.SourceSHA256 != "sha256:14296beaf5e79d731dba3de3501dde7239731ce51b0c926bced3d76f5eff29e1" || current.OutputSHA256 != "sha256:bb814addab77fd473103651eb9aac2980ed45770d5147fb54de1f703143b2ce0" { t.Fatalf("invalid v1.17 current selector: %+v", current) }
	case "runtime-v1.19":
		if current.TupleID != "sha256:37c9a07425d454c74859112debcc3ef362d43e80d5767560d9bde28a3c8d5e73" || current.RuntimeABI != "strategy-runtime-abi-v1.19" || current.ArenaCatalog != "canonical-arena-catalog-v1.37" || current.SetPolicy != "canonical-set-policy-v1.37-four-condition-v1" || current.ConformanceCertificateVersion != "runtime-conformance-certificate-v1.19" || current.SourceSHA256 != "sha256:110d30db98623cb90f07b473045cf04aca3433fb823964163191a0a8cba64b61" || current.OutputSHA256 != "sha256:15030ee59b81a2bf04667e045344de36d1b11b9834e64f71be05ccf7b73d80d5" { t.Fatalf("invalid v1.19 current selector: %+v", current) }
	default:
		t.Fatalf("unknown current selector: %+v", current)
	}
}

func TestArenaSetAuthorityV137GeneratedProductionFilesAreDataOnly(t *testing.T) {
	for _, name := range []string{"arena_set_authority_v1_37_generated.go", "current_semantic_authority_generated.go"} {
		bytes, err := os.ReadFile(name); if err != nil { t.Fatal(err) }
		source := string(bytes)
		if strings.Contains(source, "import ") { t.Fatalf("%s must have no imports", name) }
		for _, forbidden := range []string{"runMatch(", "executeStrategy", "StrategyRuntime", "recordChronicle", "database/sql", "pgx.", "net/http", "os.ReadFile"} { if strings.Contains(source, forbidden) { t.Fatalf("%s contains semantic/execution owner %q", name, forbidden) } }
	}
	first, _ := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	second, _ := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	if !reflect.DeepEqual(first, second) { t.Fatal("candidate data is nondeterministic") }
}
