// Code generated by scripts/generate-v1-37-arena-set-authority.ts; DO NOT EDIT.
package main

const arenaSetAuthorityV137SourceSHA256 = "sha256:d1ec091831cb7f32d7dcb92eda3a0a91d77c1e694d3891c240ae15e950b9caf7"
const arenaSetAuthorityV137OutputSHA256 = "sha256:f33c173bceb3b6c5e26ba6cc4cbf8370201f9c3e93ebfc29abcb8669f4ae5d7d"

type arenaSetAuthorityV137Position struct { X, Y int }
type arenaSetAuthorityV137Bounds struct { MinX, MaxX, MinY, MaxY int }
type arenaSetAuthorityV137Arena struct {
	ID string
	Version string
	Name string
	Status string
	Schedulable bool
	AliasOf string
	InitialBounds arenaSetAuthorityV137Bounds
	TerrainStones []arenaSetAuthorityV137Position
	ArenaOwnedSetupJSON string
	SemanticGeometryHash string
}
type arenaSetAuthorityV137ConditionRow struct {
	Ordinal int
	Suffix string
	Bottom string
	Top string
	InitialInitiative string
}
type arenaSetAuthorityV137Tuple struct {
	TupleID string
	Rules string
	Engine string
	RuntimeABI string
	Chronicle string
	ArenaCatalog string
	SetPolicy string
}
type arenaSetAuthorityV137Policy struct {
	SchemaVersion string
	Version string
	LifecycleStatus string
	Active bool
	ActivationOwner string
	ConditionCount int
	FairnessSemanticsSource string
	SeedCarriesFairnessSemantics bool
	RequiresEveryCanonicalCondition bool
	PlayerViolationIsTerminalEvidence bool
	SystemFailureIsTerminalEvidence bool
	PartialMatrixCounts bool
	CompletionOrderAffectsScoring bool
}
type arenaSetAuthorityV137Candidate struct {
	SchemaVersion string
	SemanticAuthorityKey string
	Tuple arenaSetAuthorityV137Tuple
	ArenaCatalogVersion string
	GeometryHashProfile string
	Arenas []arenaSetAuthorityV137Arena
	Policy arenaSetAuthorityV137Policy
	ConditionRows []arenaSetAuthorityV137ConditionRow
	SourceSHA256 string
	OutputSHA256 string
}

func arenaSetAuthorityV137CandidateBySemanticAuthorityKey(key string) (arenaSetAuthorityV137Candidate, bool) {
	if key != "runtime-v1.19" {
		return arenaSetAuthorityV137Candidate{}, false
	}
	return arenaSetAuthorityV137Candidate{
		SchemaVersion: "go-arena-set-authority-v1.37-generated-v1",
		SemanticAuthorityKey: "runtime-v1.19",
		Tuple: arenaSetAuthorityV137Tuple{
			TupleID: "sha256:37c9a07425d454c74859112debcc3ef362d43e80d5767560d9bde28a3c8d5e73",
			Rules: "cowards-rules-v1.4",
			Engine: "engine-kernel-v1.37-candidate-1",
			RuntimeABI: "strategy-runtime-abi-v1.19",
			Chronicle: "chronicle-recorder-current-events-v1.37-candidate-1",
			ArenaCatalog: "canonical-arena-catalog-v1.37",
			SetPolicy: "canonical-set-policy-v1.37-four-condition-v1",
		},
		ArenaCatalogVersion: "canonical-arena-catalog-v1.37",
		GeometryHashProfile: "arena-semantic-geometry-v1",
		Arenas: []arenaSetAuthorityV137Arena{
		{
			ID: "arena:smoke:v1",
			Version: "v1",
			Name: "Smoke",
			Status: "active",
			Schedulable: true,
			AliasOf: "",
			InitialBounds: arenaSetAuthorityV137Bounds{MinX: 0, MaxX: 11, MinY: 0, MaxY: 11},
			TerrainStones: []arenaSetAuthorityV137Position{},
			ArenaOwnedSetupJSON: "{}",
			SemanticGeometryHash: "sha256:39aecc22c184660c1c08ab810fbfa3066da1a650b20e91d72a838ed7fb70a0e1",
		},
		{
			ID: "arena:standard-cross:v1",
			Version: "v1",
			Name: "Standard Cross",
			Status: "active",
			Schedulable: true,
			AliasOf: "",
			InitialBounds: arenaSetAuthorityV137Bounds{MinX: 0, MaxX: 11, MinY: 0, MaxY: 11},
			TerrainStones: []arenaSetAuthorityV137Position{{X: 3, Y: 2}, {X: 2, Y: 3}, {X: 4, Y: 3}, {X: 3, Y: 4}},
			ArenaOwnedSetupJSON: "{}",
			SemanticGeometryHash: "sha256:87e0d0c2f555328b9863edfc25faf30300db7ce77a1d18fce9b22839560eeb4d",
		},
		{
			ID: "arena:open-field:v1",
			Version: "v1",
			Name: "Open Field",
			Status: "historical_alias",
			Schedulable: false,
			AliasOf: "arena:smoke:v1",
			InitialBounds: arenaSetAuthorityV137Bounds{MinX: 0, MaxX: 11, MinY: 0, MaxY: 11},
			TerrainStones: []arenaSetAuthorityV137Position{},
			ArenaOwnedSetupJSON: "{}",
			SemanticGeometryHash: "sha256:39aecc22c184660c1c08ab810fbfa3066da1a650b20e91d72a838ed7fb70a0e1",
		},
		},
		Policy: arenaSetAuthorityV137Policy{
			SchemaVersion: "canonical-set-policy-v1.37-contract-v1",
			Version: "canonical-set-policy-v1.37-four-condition-v1",
			LifecycleStatus: "candidate",
			Active: false,
			ActivationOwner: "Phase-260-Plan-14",
			ConditionCount: 4,
			FairnessSemanticsSource: "explicit-condition-fields",
			SeedCarriesFairnessSemantics: false,
			RequiresEveryCanonicalCondition: true,
			PlayerViolationIsTerminalEvidence: true,
			SystemFailureIsTerminalEvidence: false,
			PartialMatrixCounts: false,
			CompletionOrderAffectsScoring: false,
		},
		ConditionRows: []arenaSetAuthorityV137ConditionRow{
		{
			Ordinal: 0,
			Suffix: "a-bottom-a-first",
			Bottom: "a",
			Top: "b",
			InitialInitiative: "a",
		},
		{
			Ordinal: 1,
			Suffix: "a-bottom-b-first",
			Bottom: "a",
			Top: "b",
			InitialInitiative: "b",
		},
		{
			Ordinal: 2,
			Suffix: "a-top-a-first",
			Bottom: "b",
			Top: "a",
			InitialInitiative: "a",
		},
		{
			Ordinal: 3,
			Suffix: "a-top-b-first",
			Bottom: "b",
			Top: "a",
			InitialInitiative: "b",
		},
		},
		SourceSHA256: arenaSetAuthorityV137SourceSHA256,
		OutputSHA256: arenaSetAuthorityV137OutputSHA256,
	}, true
}
