// Code generated by scripts/generate-v1-37-arena-set-authority.ts; DO NOT EDIT.
package main

import (
	"os"
	"reflect"
	"strings"
	"testing"
)

func TestArenaSetAuthorityV137CandidateProjection(t *testing.T) {
	candidate, ok := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	if !ok { t.Fatal("explicit v1.19 candidate lookup failed") }
	if candidate.SourceSHA256 != "sha256:d1ec091831cb7f32d7dcb92eda3a0a91d77c1e694d3891c240ae15e950b9caf7" || candidate.OutputSHA256 != "sha256:f33c173bceb3b6c5e26ba6cc4cbf8370201f9c3e93ebfc29abcb8669f4ae5d7d" { t.Fatal("generated source/output digest drift") }
	if candidate.Tuple.RuntimeABI != "strategy-runtime-abi-v1.19" || candidate.Tuple.ArenaCatalog != "canonical-arena-catalog-v1.37" || candidate.Tuple.SetPolicy != "canonical-set-policy-v1.37-four-condition-v1" { t.Fatal("candidate tuple drift") }
	if len(candidate.Arenas) != 3 || candidate.Arenas[0].ID != "arena:smoke:v1" || candidate.Arenas[1].ID != "arena:standard-cross:v1" || candidate.Arenas[2].ID != "arena:open-field:v1" { t.Fatal("arena catalog membership/order drift") }
	if candidate.Arenas[0].SemanticGeometryHash != candidate.Arenas[2].SemanticGeometryHash || candidate.Arenas[2].AliasOf != candidate.Arenas[0].ID || candidate.Arenas[2].Schedulable { t.Fatal("arena alias semantics drift") }
	if len(candidate.ConditionRows) != 4 || candidate.Policy.ConditionCount != 4 || candidate.Policy.Active || candidate.Policy.SeedCarriesFairnessSemantics || candidate.Policy.PartialMatrixCounts || candidate.Policy.SystemFailureIsTerminalEvidence || !candidate.Policy.RequiresEveryCanonicalCondition || !candidate.Policy.PlayerViolationIsTerminalEvidence { t.Fatal("four-condition policy drift") }
	wantSuffixes := []string{"a-bottom-a-first", "a-bottom-b-first", "a-top-a-first", "a-top-b-first"}
	for index, row := range candidate.ConditionRows { if row.Ordinal != index || row.Suffix != wantSuffixes[index] { t.Fatal("condition membership/order drift") } }
	copyCandidate := candidate
	copyCandidate.Arenas[0].ID = "mutated"
	again, _ := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	if again.Arenas[0].ID != "arena:smoke:v1" { t.Fatal("candidate lookup shared mutable data") }
}

func TestArenaSetAuthorityV137LookupIsExplicitAndCurrentRemainsPhase259(t *testing.T) {
	for _, key := range []string{"", "runtime-v1.17", "runtime-v1.18", "runtime-v1.20"} { if _, ok := arenaSetAuthorityV137CandidateBySemanticAuthorityKey(key); ok { t.Fatalf("unexpected candidate lookup for %q", key) } }
	current := currentSemanticAuthorityGenerated()
	if current.SemanticAuthorityKey != "runtime-v1.17" || current.RuntimeABI != "strategy-runtime-abi-v1.17" || current.ArenaCatalog != "semantic-arena-catalog-v1.37-candidate-1" || current.SetPolicy != "canonical-set-policy-v1.4" || current.ConformanceCertificateVersion != "runtime-conformance-certificate-v1.17" { t.Fatalf("current selector no longer equals Phase 259: %+v", current) }
	if current.TupleID != runtimeSuccessorSemanticTupleIDV117 || current.Rules != runtimeSuccessorCanonicalTupleV117.Rules || current.Engine != runtimeSuccessorCanonicalTupleV117.Engine || current.Chronicle != runtimeSuccessorCanonicalTupleV117.Chronicle { t.Fatal("current selector split from selected Phase-259 Go authority") }
}

func TestArenaSetAuthorityV137GeneratedProductionFilesAreDataOnly(t *testing.T) {
	for _, name := range []string{"arena_set_authority_v1_37_generated.go", "current_semantic_authority_generated.go"} {
		bytes, err := os.ReadFile(name); if err != nil { t.Fatal(err) }
		source := string(bytes)
		if strings.Contains(source, "import ") { t.Fatalf("%s must have no imports", name) }
		for _, forbidden := range []string{"runMatch(", "executeStrategy", "StrategyRuntime", "recordChronicle", "database/sql", "pgx.", "net/http", "os.ReadFile"} { if strings.Contains(source, forbidden) { t.Fatalf("%s contains semantic/execution owner %q", name, forbidden) } }
	}
	first, _ := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	second, _ := arenaSetAuthorityV137CandidateBySemanticAuthorityKey("runtime-v1.19")
	if !reflect.DeepEqual(first, second) { t.Fatal("candidate data is nondeterministic") }
}
