// Code generated by scripts/generate-v1-37-arena-set-authority.ts; DO NOT EDIT.
package main

type currentSemanticAuthorityGeneratedSelection struct {
	SemanticAuthorityKey string
	TupleID string
	Rules string
	Engine string
	RuntimeABI string
	Chronicle string
	ArenaCatalog string
	SetPolicy string
	ConformanceCertificateVersion string
	SourceSHA256 string
	OutputSHA256 string
}

func currentSemanticAuthorityGenerated() currentSemanticAuthorityGeneratedSelection {
	return currentSemanticAuthorityGeneratedSelection{
		SemanticAuthorityKey: "runtime-v1.17",
		TupleID: "sha256:0d8a04fdfe49e3aa7261728ee51beb0a9049b661aad978277f2892c3a4bc54fe",
		Rules: "cowards-rules-v1.4",
		Engine: "engine-kernel-v1.37-candidate-1",
		RuntimeABI: "strategy-runtime-abi-v1.17",
		Chronicle: "chronicle-recorder-current-events-v1.37-candidate-1",
		ArenaCatalog: "semantic-arena-catalog-v1.37-candidate-1",
		SetPolicy: "canonical-set-policy-v1.4",
		ConformanceCertificateVersion: "runtime-conformance-certificate-v1.17",
		SourceSHA256: arenaSetAuthorityV137SourceSHA256,
		OutputSHA256: arenaSetAuthorityV137OutputSHA256,
	}
}
