// Code generated by scripts/generate-v1-37-arena-set-authority.ts; DO NOT EDIT.
package main

type currentSemanticAuthorityGeneratedSelection struct {
	SemanticAuthorityKey string
	TupleID string
	Rules string
	Engine string
	RuntimeABI string
	Chronicle string
	ArenaCatalog string
	SetPolicy string
	ConformanceCertificateVersion string
	SourceSHA256 string
	OutputSHA256 string
}

func currentSemanticAuthorityGenerated() currentSemanticAuthorityGeneratedSelection {
	return currentSemanticAuthorityGeneratedSelection{
		SemanticAuthorityKey: "runtime-v1.19",
		TupleID: "sha256:37c9a07425d454c74859112debcc3ef362d43e80d5767560d9bde28a3c8d5e73",
		Rules: "cowards-rules-v1.4",
		Engine: "engine-kernel-v1.37-candidate-1",
		RuntimeABI: "strategy-runtime-abi-v1.19",
		Chronicle: "chronicle-recorder-current-events-v1.37-candidate-1",
		ArenaCatalog: "canonical-arena-catalog-v1.37",
		SetPolicy: "canonical-set-policy-v1.37-four-condition-v1",
		ConformanceCertificateVersion: "runtime-conformance-certificate-v1.19",
		SourceSHA256: "sha256:110d30db98623cb90f07b473045cf04aca3433fb823964163191a0a8cba64b61",
		OutputSHA256: "sha256:15030ee59b81a2bf04667e045344de36d1b11b9834e64f71be05ccf7b73d80d5",
	}
}
