// Code generated by scripts/generate-go-parity-fixtures.ts; DO NOT EDIT.
package main

var expectedFixtureChecksumManifest = fixtureChecksumManifest{
	SchemaVersion: "go-parity-fixtures-v1.8",
	Files: map[string]string{
		"analytics-run-summary.json"     : "sha256:8c09ab802236168752bc190c496830a836af332aff53ab62575919b5bb052608",
		"degraded-match-set-summary.json": "sha256:66b2a1add5c5bdacee3e83cce970a88b132c9a54aa21fcd5be25d7e0bcd18f62",
		"forbidden-error.json"           : "sha256:56f90864bfb3af1c065f825755b6dc20a4a321eaca4df759c9dde1a267af750a",
		"health.json"                    : "sha256:56488b12b6397ceee7ddc05dfe54ca7f0f7d428a7073f16122443a7e5d37deb0",
		"not-found-error.json"           : "sha256:558857729a5410e46f11c58906b6642cddbeb888463ba96eec26256e5ffca538",
		"public-ladder-page.json"        : "sha256:1955721d8b36d9eb741072936c82569f8bc9b8e5da130c1bb191afa5aecef522",
		"public-match-set-summary.json"  : "sha256:ed428ce2d99cde5b2f4b19dca0402ce687ead91c7ee492d95f7bc91b3f83dd3a",
		"public-player-page.json"        : "sha256:8c1dd630741a281c4c9239e30a411c1b55a54fe40efa7f375f5ec9bc70b75235",
		"public-replay-evidence.json"    : "sha256:bc5a96292e793dc6a317349c03c6d854ee0764d81b59fb37b2dc28b10043143b",
		"public-replay-metadata.json"    : "sha256:21bfb503304b0367528544cba109fa6ec73543ff6af1df40ab0b74777e85baed",
		"public-strategy-page.json"      : "sha256:4710b0ef0b9ec5a037a978dbe50564fbde109688e95a92ae258b56c42742cb58",
		"route-manifest.json"            : "sha256:fe804ec317619900371ffe5f7c0e3725f12692315dbfba5bb1e830124d95d68c",
	},
}
