// Code generated by scripts/generate-go-parity-fixtures.ts; DO NOT EDIT.
package main

var runtimeServiceContractFailureCodes = map[string]struct{}{
	"MALFORMED_REQUEST": {},
	"SOURCE_HASH_MISMATCH": {},
	"SOURCE_BYTES_MISMATCH": {},
	"UNSUPPORTED_RUNTIME_ADAPTER": {},
	"MATCH_EXECUTION_FAILED": {},
	"CHRONICLE_INTEGRITY_FAILED": {},
	"EXECUTION_EXCEPTION": {},
	"RESPONSE_SCHEMA_INVALID": {},
	"EVIDENCE_STALE": {},
	"EVIDENCE_REVOKED": {},
	"EVIDENCE_IDENTITY_MISMATCH": {},
	"EVIDENCE_UNVERIFIABLE": {},
	"EVIDENCE_REGISTRY_DRIFT": {},
}
