// Code generated by scripts/generate-go-parity-fixtures.ts; DO NOT EDIT.
package main

type runtimeInvocationContractDescriptor struct {
	ContractVersion string
	RequestSHA256 string
	ResponseSHA256 string
	Historical bool
	CanonicalJSON bool
	Current bool
	ReceiptClaimSHA256 string
	ReceiptSignature string
}

func runtimeInvocationContractForVersion(version string) (runtimeInvocationContractDescriptor, bool) {
	switch version {
	case "runtime-execution-service-v1.16":
		return runtimeInvocationContractDescriptor{
			ContractVersion: "runtime-execution-service-v1.16",
			RequestSHA256: "5d04fa4d82eb814bb034ce9b5f1d5c80945e3d4e02c9124ca39a6670e9c0eab5",
			ResponseSHA256: "9c870d57e0125eb80ab2ba941ecbbede8a9a775f61c0b278abec25c491374d97",
			Historical: true,
			CanonicalJSON: false,
			Current: true,
		}, true
	case "runtime-invocation-v1.17":
		return runtimeInvocationContractDescriptor{
			ContractVersion: "runtime-invocation-v1.17",
			RequestSHA256: "76d4568f6b0e7f9760f9a0f72d1140212ff28e9a1b60897126f433d4a07f61ae",
			ResponseSHA256: "94dcf3bb2b3c7437cecf7cd59493e6be7d4d0c0de3475c747e8af888228f099e",
			Historical: false,
			CanonicalJSON: true,
			Current: false,
		}, true
	case "runtime-execution-service-v1.17":
		return runtimeInvocationContractDescriptor{
			ContractVersion: "runtime-execution-service-v1.17",
			RequestSHA256: "f11b7216621637d0329409ebf1c83fb1d448191fe1dc7c13cacedb90f6f78b00",
			ResponseSHA256: "ea702ef605111d542e8dd1dc445906c1affbd30c515071654f7ef448d9eea990",
			Historical: false,
			CanonicalJSON: true,
			Current: false,
			ReceiptClaimSHA256: "3fb1d76eebf9bce51646b47a59f4d34299761f3f8eab3434f39d4a9d6b08a2f6",
			ReceiptSignature: "hmac-sha256:9329777daf84bc1d89c587125b86330b8d0886432172f790313c562e1beebf27",
		}, true
	default:
		return runtimeInvocationContractDescriptor{}, false
	}
}

func runtimeInvocationContractsSnapshot() map[string]runtimeInvocationContractDescriptor {
	historical, _ := runtimeInvocationContractForVersion("runtime-execution-service-v1.16")
	candidate, _ := runtimeInvocationContractForVersion("runtime-invocation-v1.17")
	serviceCandidate, _ := runtimeInvocationContractForVersion("runtime-execution-service-v1.17")
	return map[string]runtimeInvocationContractDescriptor{
		historical.ContractVersion: historical,
		candidate.ContractVersion: candidate,
		serviceCandidate.ContractVersion: serviceCandidate,
	}
}

func runtimeServiceContractFailureCodeKnown(code string) bool {
	switch code {
	case "MALFORMED_REQUEST":
		return true
	case "SOURCE_HASH_MISMATCH":
		return true
	case "SOURCE_BYTES_MISMATCH":
		return true
	case "UNSUPPORTED_RUNTIME_ADAPTER":
		return true
	case "MATCH_EXECUTION_FAILED":
		return true
	case "CHRONICLE_INTEGRITY_FAILED":
		return true
	case "EXECUTION_EXCEPTION":
		return true
	case "RESPONSE_SCHEMA_INVALID":
		return true
	case "EVIDENCE_STALE":
		return true
	case "EVIDENCE_REVOKED":
		return true
	case "EVIDENCE_IDENTITY_MISMATCH":
		return true
	case "EVIDENCE_UNVERIFIABLE":
		return true
	case "EVIDENCE_REGISTRY_DRIFT":
		return true
	default:
		return false
	}
}

func runtimeServiceContractFailureCodesSnapshot() map[string]struct{} {
	return map[string]struct{}{
		"MALFORMED_REQUEST": {},
		"SOURCE_HASH_MISMATCH": {},
		"SOURCE_BYTES_MISMATCH": {},
		"UNSUPPORTED_RUNTIME_ADAPTER": {},
		"MATCH_EXECUTION_FAILED": {},
		"CHRONICLE_INTEGRITY_FAILED": {},
		"EXECUTION_EXCEPTION": {},
		"RESPONSE_SCHEMA_INVALID": {},
		"EVIDENCE_STALE": {},
		"EVIDENCE_REVOKED": {},
		"EVIDENCE_IDENTITY_MISMATCH": {},
		"EVIDENCE_UNVERIFIABLE": {},
		"EVIDENCE_REGISTRY_DRIFT": {},
	}
}

func runtimeInvocationV117SystemFailureRetryable(code string) (bool, bool) {
	switch code {
	case "OUTER_FRAME_MISSING":
		return true, true
	case "OUTER_FRAME_TRUNCATED":
		return true, true
	case "OUTER_FRAME_UNAUTHENTICATED":
		return false, true
	case "OUTER_FRAME_WRONG_BINDING":
		return false, true
	case "OUTER_FRAME_UNDECODABLE":
		return false, true
	case "ADAPTER_CRASH":
		return true, true
	case "RUNTIME_CRASH":
		return true, true
	case "HOST_CRASH":
		return true, true
	case "TRANSPORT_CRASH":
		return true, true
	case "TIMEOUT":
		return false, true
	case "AMBIGUOUS_ATTRIBUTION":
		return false, true
	default:
		return false, false
	}
}

func runtimeInvocationV117SystemFailureRetryabilitySnapshot() map[string]bool {
	return map[string]bool{
		"OUTER_FRAME_MISSING": true,
		"OUTER_FRAME_TRUNCATED": true,
		"OUTER_FRAME_UNAUTHENTICATED": false,
		"OUTER_FRAME_WRONG_BINDING": false,
		"OUTER_FRAME_UNDECODABLE": false,
		"ADAPTER_CRASH": true,
		"RUNTIME_CRASH": true,
		"HOST_CRASH": true,
		"TRANSPORT_CRASH": true,
		"TIMEOUT": false,
		"AMBIGUOUS_ATTRIBUTION": false,
	}
}
